@startuml

(*) --> "入力データ数(n)を入力"
"入力データ数(n)を入力" --> "データを入力R(i)"
If "n回入力済み" then
--> [true] "最小値にR(0)を格納"
--> "差の最大値に初期値を設定"
else
--> [false]"データを入力R(i)"
"差の最大値に初期値を設定" --> "「差の最大値」と「R(i) ― 最小値」を比較し大きい方を「差の最大値」に格納"
"「差の最大値」と「R(i) ― 最小値」を比較し大きい方を「差の最大値」に格納" --> "「最小値」と「R(i)」を比較し、小さい方を「最小値」に格納"
If "比較の回数がn回に到達" then
--> [true] "「差の最大値」を出力"
else
--> [false] "「差の最大値」と「R(i) ― 最小値」を比較し大きい方を「差の最大値」に格納"

@enduml